//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetrolinkTimes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetrolinkTimes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:&quot;1665&quot;,&quot;route_id&quot;:&quot;Antelope Valley Line&quot;,&quot;service_id&quot;:&quot;1142&quot;,&quot;trip_id&quot;:&quot;294300161&quot;,&quot;trip_headsign&quot;:&quot;L. A. Union Station&quot;,&quot;trip_short_name&quot;:&quot;200&quot;,&quot;direction_id&quot;:&quot;1&quot;,&quot;shape_id&quot;:&quot;AVin&quot;,&quot;trip_sequence&quot;:&quot;10&quot;,&quot;stop_name&quot;:&quot;Lancaster Metrolink Station&quot;,&quot;stop_lat&quot;:&quot;34.696579&quot;,&quot;stop_lon&quot;:&quot;-118.136131&quot;,&quot;arrival_time&quot;:&quot;03:47:00&quot;,&quot;departure_time&quot;:&quot;03:47:00&quot;,&quot;stop_id&quot;:&quot;102&quot;,&quot;stop_sequence&quot;:&quot;1&quot;,&quot;stop_headsign&quot;:&quot;L. A. Union Station&quot;,&quot;pickup_type&quot;:&quot;0&quot;,&quot;arrival_secs&quot;:&quot;13620&quot;,&quot;departure_secs&quot;:&quot;13620&quot;,&quot;notes&quot;:null},{&quot;id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string antelope_valley_weekday {
            get {
                return ResourceManager.GetString("antelope_valley_weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:&quot;1731&quot;,&quot;route_id&quot;:&quot;Antelope Valley Line&quot;,&quot;service_id&quot;:&quot;1143&quot;,&quot;trip_id&quot;:&quot;294500201&quot;,&quot;trip_headsign&quot;:&quot;L. A. Union Station&quot;,&quot;trip_short_name&quot;:&quot;260&quot;,&quot;direction_id&quot;:&quot;1&quot;,&quot;shape_id&quot;:&quot;AVin&quot;,&quot;trip_sequence&quot;:&quot;10&quot;,&quot;stop_name&quot;:&quot;Lancaster Metrolink Station&quot;,&quot;stop_lat&quot;:&quot;34.696579&quot;,&quot;stop_lon&quot;:&quot;-118.136131&quot;,&quot;arrival_time&quot;:&quot;06:25:00&quot;,&quot;departure_time&quot;:&quot;06:25:00&quot;,&quot;stop_id&quot;:&quot;102&quot;,&quot;stop_sequence&quot;:&quot;1&quot;,&quot;stop_headsign&quot;:&quot;L. A. Union Station&quot;,&quot;pickup_type&quot;:&quot;0&quot;,&quot;arrival_secs&quot;:&quot;23100&quot;,&quot;departure_secs&quot;:&quot;23100&quot;,&quot;notes&quot;:null},{&quot;id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string antelope_valley_weekend {
            get {
                return ResourceManager.GetString("antelope_valley_weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:&quot;2225&quot;,&quot;route_id&quot;:&quot;Inland Emp.-Orange Co. Line&quot;,&quot;service_id&quot;:&quot;1153&quot;,&quot;trip_id&quot;:&quot;296800442&quot;,&quot;trip_headsign&quot;:&quot;San Bernardino&quot;,&quot;trip_short_name&quot;:&quot;800&quot;,&quot;direction_id&quot;:&quot;1&quot;,&quot;shape_id&quot;:&quot;IEOCin&quot;,&quot;trip_sequence&quot;:&quot;10&quot;,&quot;stop_name&quot;:&quot;Oceanside Metrolink Station&quot;,&quot;stop_lat&quot;:&quot;33.192554&quot;,&quot;stop_lon&quot;:&quot;-117.379875&quot;,&quot;arrival_time&quot;:&quot;07:39:00&quot;,&quot;departure_time&quot;:&quot;07:39:00&quot;,&quot;stop_id&quot;:&quot;111&quot;,&quot;stop_sequence&quot;:&quot;1&quot;,&quot;stop_headsign&quot;:&quot;San Bernardino&quot;,&quot;pickup_type&quot;:&quot;0&quot;,&quot;arrival_secs&quot;:&quot;27540&quot;,&quot;departure_secs&quot;:&quot;27540&quot;,&quot;notes&quot;:null},{&quot;id&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inland_empire_weekday {
            get {
                return ResourceManager.GetString("inland_empire_weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:&quot;971&quot;,&quot;route_id&quot;:&quot;Inland Emp.-Orange Co. Line&quot;,&quot;service_id&quot;:&quot;1154&quot;,&quot;trip_id&quot;:&quot;296800429&quot;,&quot;trip_headsign&quot;:&quot;San Bernardino&quot;,&quot;trip_short_name&quot;:&quot;860&quot;,&quot;direction_id&quot;:&quot;1&quot;,&quot;shape_id&quot;:&quot;IEOCin&quot;,&quot;trip_sequence&quot;:&quot;20&quot;,&quot;stop_name&quot;:&quot;Oceanside Metrolink Station&quot;,&quot;stop_lat&quot;:&quot;33.192554&quot;,&quot;stop_lon&quot;:&quot;-117.379875&quot;,&quot;arrival_time&quot;:&quot;16:28:00&quot;,&quot;departure_time&quot;:&quot;16:28:00&quot;,&quot;stop_id&quot;:&quot;111&quot;,&quot;stop_sequence&quot;:&quot;1&quot;,&quot;stop_headsign&quot;:&quot;San Bernardino&quot;,&quot;pickup_type&quot;:&quot;0&quot;,&quot;arrival_secs&quot;:&quot;59280&quot;,&quot;departure_secs&quot;:&quot;59280&quot;,&quot;notes&quot;:&quot;sharedstati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inland_empire_weekend {
            get {
                return ResourceManager.GetString("inland_empire_weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:&quot;1034&quot;,&quot;route_id&quot;:&quot;Orange County Line&quot;,&quot;service_id&quot;:&quot;1151&quot;,&quot;trip_id&quot;:&quot;296100042&quot;,&quot;trip_headsign&quot;:&quot;L. A. Union Station&quot;,&quot;trip_short_name&quot;:&quot;601&quot;,&quot;direction_id&quot;:&quot;1&quot;,&quot;shape_id&quot;:&quot;OCin&quot;,&quot;trip_sequence&quot;:&quot;20&quot;,&quot;stop_name&quot;:&quot;Oceanside Metrolink Station&quot;,&quot;stop_lat&quot;:&quot;33.192554&quot;,&quot;stop_lon&quot;:&quot;-117.379875&quot;,&quot;arrival_time&quot;:&quot;04:38:00&quot;,&quot;departure_time&quot;:&quot;04:38:00&quot;,&quot;stop_id&quot;:&quot;111&quot;,&quot;stop_sequence&quot;:&quot;1&quot;,&quot;stop_headsign&quot;:&quot;L. A. Union Station&quot;,&quot;pickup_type&quot;:&quot;0&quot;,&quot;arrival_secs&quot;:&quot;16680&quot;,&quot;departure_secs&quot;:&quot;16680&quot;,&quot;notes&quot;:null},{&quot;id&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string orange_county_weekday {
            get {
                return ResourceManager.GetString("orange_county_weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [{&quot;id&quot;:&quot;997&quot;,&quot;route_id&quot;:&quot;Orange County Line&quot;,&quot;service_id&quot;:&quot;1152&quot;,&quot;trip_id&quot;:&quot;296300901&quot;,&quot;trip_headsign&quot;:&quot;L. A. Union Station&quot;,&quot;trip_short_name&quot;:&quot;661&quot;,&quot;direction_id&quot;:&quot;1&quot;,&quot;shape_id&quot;:&quot;OCin&quot;,&quot;trip_sequence&quot;:&quot;10&quot;,&quot;stop_name&quot;:&quot;Oceanside Metrolink Station&quot;,&quot;stop_lat&quot;:&quot;33.192554&quot;,&quot;stop_lon&quot;:&quot;-117.379875&quot;,&quot;arrival_time&quot;:&quot;08:15:00&quot;,&quot;departure_time&quot;:&quot;08:15:00&quot;,&quot;stop_id&quot;:&quot;111&quot;,&quot;stop_sequence&quot;:&quot;1&quot;,&quot;stop_headsign&quot;:&quot;L. A. Union Station&quot;,&quot;pickup_type&quot;:&quot;0&quot;,&quot;arrival_secs&quot;:&quot;29700&quot;,&quot;departure_secs&quot;:&quot;29700&quot;,&quot;notes&quot;:&quot;sharedstati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string orange_county_weekend {
            get {
                return ResourceManager.GetString("orange_county_weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [{&quot;id&quot;:&quot;1877&quot;,&quot;route_id&quot;:&quot;91 Line&quot;,&quot;service_id&quot;:&quot;1150&quot;,&quot;trip_id&quot;:&quot;296000081&quot;,&quot;trip_headsign&quot;:&quot;San Bernardino&quot;,&quot;trip_short_name&quot;:&quot;700&quot;,&quot;direction_id&quot;:&quot;0&quot;,&quot;shape_id&quot;:&quot;91out&quot;,&quot;trip_sequence&quot;:&quot;10&quot;,&quot;stop_name&quot;:&quot;L. A. Union Station Metrolink Station&quot;,&quot;stop_lat&quot;:&quot;34.055729&quot;,&quot;stop_lon&quot;:&quot;-118.233513&quot;,&quot;arrival_time&quot;:&quot;05:45:00&quot;,&quot;departure_time&quot;:&quot;05:45:00&quot;,&quot;stop_id&quot;:&quot;131&quot;,&quot;stop_sequence&quot;:&quot;1&quot;,&quot;stop_headsign&quot;:&quot;Riverside-Downtown&quot;,&quot;pickup_type&quot;:&quot;0&quot;,&quot;arrival_secs&quot;:&quot;20700&quot;,&quot;departure_secs&quot;:&quot;20700&quot;,&quot;notes&quot;:null},{&quot;id&quot;:&quot;1885 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string perris_valley_weekday {
            get {
                return ResourceManager.GetString("perris_valley_weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:&quot;702&quot;,&quot;route_id&quot;:&quot;91 Line&quot;,&quot;service_id&quot;:&quot;1155&quot;,&quot;trip_id&quot;:&quot;296000752&quot;,&quot;trip_headsign&quot;:&quot;San Bernardino&quot;,&quot;trip_short_name&quot;:&quot;752&quot;,&quot;direction_id&quot;:&quot;0&quot;,&quot;shape_id&quot;:&quot;91out&quot;,&quot;trip_sequence&quot;:&quot;10&quot;,&quot;stop_name&quot;:&quot;L. A. Union Station Metrolink Station&quot;,&quot;stop_lat&quot;:&quot;34.055729&quot;,&quot;stop_lon&quot;:&quot;-118.233513&quot;,&quot;arrival_time&quot;:&quot;15:15:00&quot;,&quot;departure_time&quot;:&quot;15:15:00&quot;,&quot;stop_id&quot;:&quot;131&quot;,&quot;stop_sequence&quot;:&quot;1&quot;,&quot;stop_headsign&quot;:&quot;Riverside-Downtown&quot;,&quot;pickup_type&quot;:&quot;0&quot;,&quot;arrival_secs&quot;:&quot;54900&quot;,&quot;departure_secs&quot;:&quot;54900&quot;,&quot;notes&quot;:null},{&quot;id&quot;:&quot;694&quot;,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string perris_valley_weekend {
            get {
                return ResourceManager.GetString("perris_valley_weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:&quot;1532&quot;,&quot;route_id&quot;:&quot;Riverside Line&quot;,&quot;service_id&quot;:&quot;1149&quot;,&quot;trip_id&quot;:&quot;295700441&quot;,&quot;trip_headsign&quot;:&quot;L. A. Union Station&quot;,&quot;trip_short_name&quot;:&quot;401&quot;,&quot;direction_id&quot;:&quot;1&quot;,&quot;shape_id&quot;:&quot;RIVERin&quot;,&quot;trip_sequence&quot;:&quot;10&quot;,&quot;stop_name&quot;:&quot;Riverside-Downtown Metrolink Station&quot;,&quot;stop_lat&quot;:&quot;33.975552&quot;,&quot;stop_lon&quot;:&quot;-117.369888&quot;,&quot;arrival_time&quot;:&quot;04:47:00&quot;,&quot;departure_time&quot;:&quot;04:47:00&quot;,&quot;stop_id&quot;:&quot;120&quot;,&quot;stop_sequence&quot;:&quot;1&quot;,&quot;stop_headsign&quot;:&quot;L. A. Union Station&quot;,&quot;pickup_type&quot;:&quot;0&quot;,&quot;arrival_secs&quot;:&quot;17220&quot;,&quot;departure_secs&quot;:&quot;17220&quot;,&quot;notes&quot;:null [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string riverside_weekday {
            get {
                return ResourceManager.GetString("riverside_weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:&quot;203&quot;,&quot;route_id&quot;:&quot;San Bernardino Line&quot;,&quot;service_id&quot;:&quot;1146&quot;,&quot;trip_id&quot;:&quot;295100222&quot;,&quot;trip_headsign&quot;:&quot;L. A. Union Station&quot;,&quot;trip_short_name&quot;:&quot;301&quot;,&quot;direction_id&quot;:&quot;1&quot;,&quot;shape_id&quot;:&quot;SBin&quot;,&quot;trip_sequence&quot;:&quot;10&quot;,&quot;stop_name&quot;:&quot;San Bernardino Metrolink Station&quot;,&quot;stop_lat&quot;:&quot;34.104530&quot;,&quot;stop_lon&quot;:&quot;-117.310089&quot;,&quot;arrival_time&quot;:&quot;03:50:00&quot;,&quot;departure_time&quot;:&quot;03:50:00&quot;,&quot;stop_id&quot;:&quot;122&quot;,&quot;stop_sequence&quot;:&quot;1&quot;,&quot;stop_headsign&quot;:&quot;L. A. Union Station&quot;,&quot;pickup_type&quot;:&quot;0&quot;,&quot;arrival_secs&quot;:&quot;13800&quot;,&quot;departure_secs&quot;:&quot;13800&quot;,&quot;notes&quot;:null},{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string san_bernadino_weekday {
            get {
                return ResourceManager.GetString("san_bernadino_weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:&quot;546&quot;,&quot;route_id&quot;:&quot;San Bernardino Line&quot;,&quot;service_id&quot;:&quot;1147&quot;,&quot;trip_id&quot;:&quot;295400748&quot;,&quot;trip_headsign&quot;:&quot;Riverside-Downtown&quot;,&quot;trip_short_name&quot;:&quot;352&quot;,&quot;direction_id&quot;:&quot;0&quot;,&quot;shape_id&quot;:&quot;SBout&quot;,&quot;trip_sequence&quot;:&quot;10&quot;,&quot;stop_name&quot;:&quot;L. A. Union Station Metrolink Station&quot;,&quot;stop_lat&quot;:&quot;34.055729&quot;,&quot;stop_lon&quot;:&quot;-118.233513&quot;,&quot;arrival_time&quot;:&quot;06:15:00&quot;,&quot;departure_time&quot;:&quot;06:15:00&quot;,&quot;stop_id&quot;:&quot;131&quot;,&quot;stop_sequence&quot;:&quot;1&quot;,&quot;stop_headsign&quot;:&quot;San Bernardino&quot;,&quot;pickup_type&quot;:&quot;0&quot;,&quot;arrival_secs&quot;:&quot;22500&quot;,&quot;departure_secs&quot;:&quot;22500&quot;,&quot;notes&quot;:null},{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string san_bernadino_weekend {
            get {
                return ResourceManager.GetString("san_bernadino_weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1009755438935.
        /// </summary>
        internal static string senderId {
            get {
                return ResourceManager.GetString("senderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAAA6xodP1c:APA91bF1QaEk4UgceMMZCjUt4h8JGt0cJRqFhe3GG7PrrLaUYL-rBuZjGLo_a7jXhGp10rJ3-ksIf3nVugq_S0ISfyfsHDIMSoBq8QJP6H8ctH0e0OemRsxHVoxLhdAxFT2JCApJY0rq.
        /// </summary>
        internal static string serverKey {
            get {
                return ResourceManager.GetString("serverKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM_ENTRY.
        /// </summary>
        internal static string SYSTEM {
            get {
                return ResourceManager.GetString("SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:&quot;1130&quot;,&quot;route_id&quot;:&quot;Ventura County Line&quot;,&quot;service_id&quot;:&quot;1141&quot;,&quot;trip_id&quot;:&quot;294100122&quot;,&quot;trip_headsign&quot;:&quot;L. A. Union Station&quot;,&quot;trip_short_name&quot;:&quot;102&quot;,&quot;direction_id&quot;:&quot;1&quot;,&quot;shape_id&quot;:&quot;VTin&quot;,&quot;trip_sequence&quot;:&quot;30&quot;,&quot;stop_name&quot;:&quot;East Ventura Metrolink Station&quot;,&quot;stop_lat&quot;:&quot;34.250793&quot;,&quot;stop_lon&quot;:&quot;-119.205025&quot;,&quot;arrival_time&quot;:&quot;05:21:00&quot;,&quot;departure_time&quot;:&quot;05:21:00&quot;,&quot;stop_id&quot;:&quot;103&quot;,&quot;stop_sequence&quot;:&quot;1&quot;,&quot;stop_headsign&quot;:&quot;L. A. Union Station&quot;,&quot;pickup_type&quot;:&quot;0&quot;,&quot;arrival_secs&quot;:&quot;19260&quot;,&quot;departure_secs&quot;:&quot;19260&quot;,&quot;notes&quot;:null},{&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ventura_county_weekday {
            get {
                return ResourceManager.GetString("ventura_county_weekday", resourceCulture);
            }
        }
    }
}
